#!/usr/bin/env python3
"""Edanic Pages renderer - builds a static site from {content}/**/*.md (Edanic frontmatter).

- Routes follow the `slug` frontmatter (/answers/x -> _site/answers/x/index.html)
- Injects <title>/<meta description>/ld+json server-side (visible to GPTBot/ClaudeBot)
- Rewrites root-relative internal links: known Edanic slugs get the Pages base path,
  customer-site paths point back to the customer origin
- Emits index.html (grouped listing), sitemap.xml, and copies edanic-seo/llms.txt
"""
import html
import json
import os
import re
from pathlib import Path

import markdown
import yaml

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "_site"
_OWNER, _REPO = (os.environ.get("GITHUB_REPOSITORY") or "owner/repo").split("/", 1)
BASE = "/" + _REPO
ORIGIN = (os.environ.get("EDANIC_SITE_ORIGIN") or "").rstrip("/")
PAGES_URL = os.environ.get("EDANIC_PAGES_URL") or f"https://{_OWNER}.github.io{BASE}"
CONTENT = ROOT / (os.environ.get("EDANIC_CONTENT_DIR") or "content").strip("/")

CSS = """
:root{--ink:#1f2328;--muted:#57606a;--line:#d8dee4;--accent:#b7521e;--bg:#faf9f7}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);
font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","Hiragino Sans","Noto Sans JP","Yu Gothic UI",sans-serif;line-height:1.85}
header{border-bottom:1px solid var(--line);background:#fff}
header .wrap{max-width:820px;margin:0 auto;padding:14px 20px;display:flex;gap:12px;align-items:baseline}
header a{color:var(--ink);text-decoration:none;font-weight:700}
header .tag{color:var(--muted);font-size:13px}
main{max-width:820px;margin:0 auto;padding:32px 20px 64px}
h1{font-size:26px;line-height:1.5;margin:.2em 0 .4em}
h2{font-size:20px;margin-top:2em;padding-bottom:.3em;border-bottom:1px solid var(--line)}
a{color:var(--accent)}
.meta{color:var(--muted);font-size:13px;margin-bottom:28px}
.card{display:block;background:#fff;border:1px solid var(--line);border-radius:10px;padding:16px 18px;margin:10px 0;text-decoration:none;color:var(--ink)}
.card:hover{border-color:var(--accent)}
.card b{display:block;margin-bottom:4px}.card span{color:var(--muted);font-size:14px}
.sec{color:var(--muted);font-size:13px;letter-spacing:.06em;text-transform:uppercase;margin-top:36px}
footer{border-top:1px solid var(--line);color:var(--muted);font-size:13px}
footer .wrap{max-width:820px;margin:0 auto;padding:18px 20px}
table{border-collapse:collapse}td,th{border:1px solid var(--line);padding:6px 10px}
strong{font-weight:700}
"""

SHELL = """<!DOCTYPE html>
<html lang="{lang}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<meta name="description" content="{description}">
{jsonld}
<style>{css}</style>
</head>
<body>
<header><div class="wrap"><a href="{base}/">Edanic</a><span class="tag">answer pages for {origin_host}</span></div></header>
<main>{main}</main>
<footer><div class="wrap">Generated by <a href="https://edanic.com">Edanic</a> · content source: {origin_host}</div></footer>
</body>
</html>"""


def parse(path: Path):
    txt = path.read_text(encoding="utf-8").replace("\r\n", "\n").replace("\r", "\n")   # CRLF/CR → LF
    m = re.match(r"^---\n(.*?)\n---\n?(.*)$", txt, re.S)
    if not m:
        return None
    try:
        fm = yaml.safe_load(m.group(1)) or {}
    except Exception:
        return None
    return fm, m.group(2).strip()


def main():
    pages = []
    for p in sorted(CONTENT.rglob("*.md")):
        r = parse(p)
        if r and (r[0].get("slug") or "").startswith("/"):
            pages.append(r)
    known = {fm["slug"] for fm, _ in pages}

    def rewrite(href: str) -> str:
        if not href.startswith("/") or href.startswith("//"):
            return href
        return (BASE + href) if href in known else ((ORIGIN + href) if ORIGIN else href)

    OUT.mkdir(parents=True, exist_ok=True)
    md = markdown.Markdown(extensions=["extra"])
    ohost = ORIGIN.replace("https://", "").replace("http://", "") or _REPO
    for fm, body in pages:
        md.reset()
        body_html = md.convert(body)
        body_html = re.sub(r'href="(/[^"]*)"', lambda m2: 'href="' + rewrite(m2.group(1)) + '"', body_html)
        jl = fm.get("jsonld") or []
        jsonld = "\n".join(
            '<script type="application/ld+json">' + json.dumps(x, ensure_ascii=False) + "</script>" for x in jl)
        updated = html.escape(str(fm.get("last_updated") or ""))
        inner = ("<article><h1>" + html.escape(str(fm.get("title") or "")) + "</h1>"
                 + (('<div class="meta">last updated: ' + updated + "</div>") if updated else "")
                 + body_html + "</article>")
        page = SHELL.format(lang=html.escape(str(fm.get("lang") or "en")),
                            title=html.escape(str(fm.get("title") or "")),
                            description=html.escape(str(fm.get("description") or "")),
                            jsonld=jsonld, css=CSS, base=BASE, origin_host=ohost, main=inner)
        dest = OUT / fm["slug"].strip("/") / "index.html"
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(page, encoding="utf-8")

    groups = {}
    for fm, _ in pages:
        groups.setdefault(fm["slug"].strip("/").split("/")[0], []).append(fm)
    cards = []
    for sec in sorted(groups):
        cards.append('<div class="sec">' + html.escape(sec) + "</div>")
        for fm in sorted(groups[sec], key=lambda x: str(x.get("title") or "")):
            cards.append('<a class="card" href="' + BASE + fm["slug"] + '"><b>'
                         + html.escape(str(fm.get("title") or "")) + "</b><span>"
                         + html.escape(str(fm.get("description") or "")[:110]) + "</span></a>")
    idx = SHELL.format(lang="en", title="Edanic - answer pages", description="Answer pages built by Edanic",
                       jsonld="", css=CSS, base=BASE, origin_host=ohost,
                       main="<h1>Answer pages (" + str(len(pages)) + ")</h1>" + "".join(cards))
    (OUT / "index.html").write_text(idx, encoding="utf-8")

    urls = "".join("<url><loc>" + PAGES_URL + fm["slug"] + "</loc></url>" for fm, _ in pages)
    (OUT / "sitemap.xml").write_text(
        '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'
        + urls + "</urlset>", encoding="utf-8")
    seo = ROOT / "edanic-seo" / "llms.txt"
    if seo.exists():
        (OUT / "llms.txt").write_text(seo.read_text(encoding="utf-8"), encoding="utf-8")
    print("built", len(pages), "pages ->", OUT)


if __name__ == "__main__":
    main()
